# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Danit Gal 
tagline:          'The new ethics of AI'
description:      'Insert very nice self-description.' 
url:              http://danitgal.com
baseurl:          /

author:
  name:           'Danit Gal'
#  url:            https://twitter.com/mdo

paginate:         5

#  Custom vars
#  version:          2.1.0

# github:           https://github.com/danitgal

gems:           [jekyll-paginate]
